HP_CHAIN: PPPPPPPPPPPPHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHPPPPPPPPPPPPPPPPPPPPPPPPHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
RANDOM_SEED: 72

# DESCRIPTION
#
# HP_CHAIN  The chain representing the protein to predict.
#
# RANDOM_SEED    seed for the random number generator. If negative, seed is chosen randomly.
