#include <iostream>
#include <vector>

#include "acopredictor.h"

using std::cout;
using std::cerr;
using std::vector;

ACOPredictor::ACOPredictor(const HPChain &hpchain, int cycles, int nAnts, double alpha, double beta)
: dhpchain(hpchain),
  dCycles(cycles),
  dNAnts(nAnts),
  dAlpha(alpha),
  dBeta(beta),
  dNMovElems(hpchain.length() - 2)
{
	dPheromone = new double[dNMovElems*5];
	std::fill(dPheromone, dPheromone + dNMovElems*5, 0.1);

	for(int j = 0; j < 5; j++){
		for(int i = 0; i < hpchain.length()-2; i++){
			cout << pheromone(i, j) << " ";
		} cout << "\n";
	}
}

ACOPredictor::~ACOPredictor(){
	delete[] dPheromone;
}

inline double ACOPredictor::pheromone(int i, int d) const {
	return dPheromone[i*5 + d];
}

inline ACOSolution ACOPredictor::ant_develop_solution() const {
	ACOSolution sol;

	for(int i = 0; i < dNMovElems; i++){
		// calculate probabilities
		// decide direction
	}

	return sol;
}

ACOSolution ACOPredictor::predict(){
	ACOSolution bestSol();

	for(int i = 0; i < dCycles; i++){
		vector<ACOSolution> antsSolutions; // Solutions generated by all ants

		for(int j = 0; j < dNAnts; j++){
			ACOSolution currentSol = ant_develop_solution();
			antsSolutions.push_back(currentSol);
		}

		if(i%100 == 0) cout << "Cycle: " << i << "\n";
	}

	return ACOSolution();
}
